TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  logging_steps: 10
  gradiant_accummulation_steps: 16
  save_steps: 1e6
  weight_decay: 0.01
  eval_steps: 500
  evaluation_strategy: steps